### ISSUE TITLE
Unable to test code that relies on @cfworker/web

### ISSUE THREAD

**Issue by cptchloroplast** [cfworker/cfworker#129]
I am unable to successfully unit test code that depends on `@cfworker/web`. I had to switch back from using `@cfworker/dev` to manually  invoking `webpack` to build my code since one of my dependencies required node polyfills and `@cfworker/dev` does not include them nor expose an easy way to add additional plugins. I am using `ts-mocha` as a test runner, my tests are written in Typescript, and get the following error when trying to import things from `@cfworker/web`:
```
> npx ts-mocha -p test/tsconfig.json -r test/hooks.ts test/*.test.ts test/**/*.test.ts

/home/ben/Projects/rayun/api/node_modules/@cfworker/web/dist/index.js:1
export * from './accepts.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ben/Projects/rayun/api/test/utils.test.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/home/ben/Projects/rayun/api/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ben/Projects/rayun/api/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (/home/ben/Projects/rayun/api/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/ben/Projects/rayun/api/node_modules/mocha/lib/esm-utils.js:55:34)
    at singleRun (/home/ben/Projects/rayun/api/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/home/ben/Projects/rayun/api/node_modules/mocha/lib/cli/run.js:362:5)
```

The `tsconfig.json` that I am using for testing is the following:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "CommonJS",
    "sourceMap": true,
    "experimentalDecorators": true,
    "lib": ["esnext", "webworker"],
    "types": ["@types/mocha"]
  },
  "include": [
    "./*.ts",
    "./**/*.ts",
    "../node_modules/@cloudflare/workers-types/index.d.ts"
  ]
}
```

The test in question looks something like this:
```ts
import { spy } from "sinon"
import { Context } from "@cfworker/web"
import { rebase } from "../src/utils"
import { mockFetchEvent } from "./mocks"
import { expect } from "chai"

describe("utils", () => {
  describe("rebase", () => {
    it("should rebase the url and call the middleware if the pathname matches", () => {
      const middleware = spy()
      const test = rebase("/test", middleware)
      const ctx = new Context(mockFetchEvent("/test/route"))
      const next = spy()
      test(ctx, next)
      expect(middleware.called).to.be.true
      expect(ctx.req.url.pathname).to.equal("/route")
      expect(next.called).to.be.false
    })
  })
})
```

Are you able to compile the package in CommonJS format and if so, would that fix this? I am also open to suggestions for making the test work without having to modify `@cfworker/web`. 

Thanks!

**Comment by jdanyow** [comment]
try adding `"../node_modules/@cfworker/**/*"` to the tsconfig `"include"` and could also try `allowJs: true` in the compiler options.
