### ISSUE TITLE
Unresolved $ref "https://json-schema.org/draft/2020-12/schema".

### ISSUE THREAD

**Issue by winston0410** [cfworker/cfworker#236]
I am trying to create a meta-schema to validate if an object is a schema. This is a meta-schema:

```ts
export const metaSchema = {
	allOf: [
        {"$ref": "https://json-schema.org/draft/2020-12/schema"}
    ]
} as const;
```

When I test it like this, I get an error:

```ts
import { Schema, Validator } from "@cfworker/json-schema";
import { metaSchema } from "./service.ts";
import { assertEquals } from "std/testing/asserts.ts";

Deno.test("should allow a JSON Schema", () => {
	const validator = new Validator(metaSchema as unknown as Schema);

	const schema = {
		properties: {
			name: { type: "string"}
		},
		required: ["name"],
		additionalProperties: true
	};

	const { valid } = validator.validate(schema);

	assertEquals(valid, true);
});
```

```
should allow a JSON Schema => ./src/service_test.ts:5:6
error: Error: Unresolved $ref "https://json-schema.org/draft/2020-12/schema".
Known schemas:
- https://github.com/cfworker
- https://github.com/cfworker#/allOf/0
- https://github.com/cfworker#/unevaluatedProperties
    at w (https://esm.sh/v92/@cfworker/json-schema@1.12.4/deno/json-schema.js:5:8)
    at w (https://esm.sh/v92/@cfworker/json-schema@1.12.4/deno/json-schema.js:5:2106)
    at xe.validate (https://esm.sh/v92/@cfworker/json-schema@1.12.4/deno/json-schema.js:5:11367)
    at file:///Users/hugosum/Desktop/closesource/apps/deno/api-dynamic-form/src/service_test.ts:17:30
```

I believe this is a proper usage of JSON schema, as I found [JSON hyper schema doing this as well](https://json-schema.org/draft/2019-09/hyper-schema)

**Comment by winston0410** [comment]
I have tried to copy and use the [meta schema of 2020-12](https://json-schema.org/draft/2020-12/schema) without referencing, and still I got the following error. Is `$ref` not implemented yet?

```
should not allow a malformed JSON Schema => ./src/service_test.ts:21:6
error: Error: Unresolved $ref "meta/core".  Absolute URI "https://json-schema.org/draft/2020-12/meta/core".
Known schemas:
- https://json-schema.org/draft/2020-12/schema
- https://json-schema.org/draft/2020-12/schema#/allOf/0
- https://json-schema.org/draft/2020-12/schema#/allOf/1
- https://json-schema.org/draft/2020-12/schema#/allOf/2
- https://json-schema.org/draft/2020-12/schema#/allOf/3
- https://json-schema.org/draft/2020-12/schema#/allOf/4
- https://json-schema.org/draft/2020-12/schema#/allOf/5
- https://json-schema.org/draft/2020-12/schema#/allOf/6
- https://json-schema.org/draft/2020-12/schema#/properties/definitions
- https://json-schema.org/draft/2020-12/schema#/properties/definitions/additionalProperties
- https://json-schema.org/draft/2020-12/schema#/properties/definitions/deprecated
- https://json-schema.org/draft/2020-12/schema#/properties/dependencies
- https://json-schema.org/draft/2020-12/schema#/properties/dependencies/additionalProperties
- https://json-schema.org/draft/2020-12/schema#/properties/dependencies/additionalProperties/anyOf/0
- https://json-schema.org/draft/2020-12/schema#/properties/dependencies/additionalProperties/anyOf/1
- https://json-schema.org/draft/2020-12/schema#/properties/dependencies/deprecated
- https://json-schema.org/draft/2020-12/schema#/properties/$recursiveAnchor
- https://json-schema.org/draft/2020-12/schema#/properties/$recursiveAnchor/deprecated
- https://json-schema.org/draft/2020-12/schema#/properties/$recursiveRef
- https://json-schema.org/draft/2020-12/schema#/properties/$recursiveRef/deprecated
```

**Comment by jdanyow** [comment]
@winston0410 Validator doesn't attempt to fetch schemas so you'll need to call `validator.addSchema(...)` to add both https://json-schema.org/draft/2020-12/schema and https://json-schema.org/draft/2020-12/meta/core prior to using `validator.validate(...)`.
